# Generated by Django 4.2.2 on 2023-09-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
    ]
