# Generated by Django 4.2.2 on 2023-09-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogg', '0002_remove_user_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
