# Generated by Django 4.2.2 on 2023-10-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogg', '0003_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blogg.user'),
            preserve_default=False,
        ),
    ]
